import smtplib

#if __name__=='__main__':
    
def send_alert(body):
    email_address='pandeypankaj46@gmail.com'
    #This is not your email password rather its a passcode generated by gmail App Password link 
    #https://myaccount.google.com/apppasswords
    #Go to avove link and generate a passcode and use that here
    email_password='jtgyyydhkeneciui'

    with smtplib.SMTP('smtp.gmail.com',587) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()

        smtp.login(email_address, email_password)

        subject='Alert invalid data found'
        email_body= f'Data Validation Failed in {body}'
        msg=f'Subject: {subject}\n\n{email_body}'

        smtp.sendmail(email_address, 'pp00937838@techmahindra.com', msg)

send_alert('Pankaj sending')